[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_init = "32GwVwnceAvFFFNNDgp1FAFrRkpYAYE9xS4GRqnQosoL"
escrow = "2zNTYwuKpcXm73EjEZTUAbvTnerhTGnAD8eRU2Y9VRo2"
lottery = "HUJGjErk2znng9Ew3sUdfTfZUiXSSgigdG1ospGKsPwt"
voting = "H2VaWfnrg7F39nozEfkdZgShUEe6BZTCj2PfNikkpY7H"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = ".cache/keys/payer.json"

[scripts]
test = "await_net; yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
