[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_init = "32GwVwnceAvFFFNNDgp1FAFrRkpYAYE9xS4GRqnQosoL"
voting = "5SBHwL1A7QNAkyEYdXXJ9PVTqwrhpkHrejwH5jjwunY5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "await_net; yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
