[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_init = "4wRYvRWymeFK9vpCDV2Z1fAE6yKyzM6epS6vSv1D6UPB"
voting = "FzdA2479vq93UucMszbw9bGYZEJNg5kEiPV37abo9Ytj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "await_net; yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
